//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Clock
{
	private TimeManager timeMgr
	{
		get;
		set;
	}

	private SixtySecondTimer timer
	{
		get;
		set;
	}

	private ModeManager modeMgr
	{
		get;
		set;
	}

	private Display display
	{
		get;
		set;
	}

	private Alarm alarm
	{
		get;
		set;
	}

	private ButtonManager button
	{
		get;
		set;
	}

	public virtual ButtonManager button
	{
		get;
		set;
	}

	public virtual ModeManager modeMgr
	{
		get;
		set;
	}

	public virtual TimeManager timeMgr
	{
		get;
		set;
	}

	public virtual Display display
	{
		get;
		set;
	}

	public virtual Alarm alarm
	{
		get;
		set;
	}

	public Clock()
	{
	}

	public virtual void Start()
	{
		throw new System.NotImplementedException();
	}

}

