//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ModeManager
{
	public virtual Mode currentMode
	{
		get;
		set;
	}

	public virtual Mode currentMode
	{
		get;
		set;
	}

	public ModeManager()
	{
	}

	public virtual void SetMode(Mode newMode)
	{
		throw new System.NotImplementedException();
	}

	public virtual Mode GetMode()
	{
		throw new System.NotImplementedException();
	}

}

