//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TimeManager
{
	private Time currentTime
	{
		get;
		set;
	}

	private Time alarmTime
	{
		get;
		set;
	}

	private Time snoozeTime
	{
		get;
		set;
	}

	private Display display
	{
		get;
		set;
	}

	private Alarm alarm
	{
		get;
		set;
	}

	private ModeManager modeMgr
	{
		get;
		set;
	}

	public virtual Time currentTime
	{
		get;
		set;
	}

	public virtual Time alarmTime
	{
		get;
		set;
	}

	public virtual Time snoozeTime
	{
		get;
		set;
	}

	public TimeManager()
	{
	}

	public virtual void SetDisplay(Display newDisplay)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetModeManager(ModeManager newModeManager)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetAlarm(Alarm newAlarm)
	{
		throw new System.NotImplementedException();
	}

	public virtual void IncrementCurrentMinute()
	{
		throw new System.NotImplementedException();
	}

	public virtual void IncrementCurrentHour()
	{
		throw new System.NotImplementedException();
	}

	public virtual void IncrementAlarmHour()
	{
		throw new System.NotImplementedException();
	}

	public virtual void IncrementAlarmMinute()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Snooze()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ShowCurrentTime()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ShowAlarmTime()
	{
		throw new System.NotImplementedException();
	}

}

